version: '3.7'

services:
  lighttpd:
    build: 
      context: .
      network: host
    container_name: lighttpd
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${VOLUME_DATA}:/var/www/localhost/htdocs
